/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ceq1_v_func_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[44] = {40, 1, 0, 40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const casadi_int casadi_s2[184] = {180, 1, 0, 180, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[83] = {3, 20, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s6[461] = {40, 220, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 38, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 56, 57, 58, 59, 60, 61, 62, 63, 64, 66, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 80, 81, 82, 83, 84, 86, 87, 88, 89, 90, 91, 92, 93, 94, 96, 97, 98, 99, 100, 101, 102, 103, 104, 106, 107, 108, 109, 110, 111, 112, 113, 114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 126, 127, 128, 129, 130, 131, 132, 133, 134, 136, 137, 138, 139, 140, 141, 142, 143, 144, 146, 147, 148, 149, 150, 151, 152, 153, 154, 156, 157, 158, 159, 160, 161, 162, 163, 164, 166, 167, 168, 169, 170, 171, 172, 173, 174, 176, 177, 178, 179, 180, 181, 182, 183, 184, 186, 187, 188, 189, 190, 191, 192, 193, 194, 196, 197, 198, 199, 200, 201, 202, 203, 204, 206, 207, 208, 209, 210, 211, 212, 213, 214, 216, 217, 218, 219, 220, 221, 222, 223, 224, 226, 227, 228, 229, 230, 231, 232, 233, 234, 236, 237, 238, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 3, 2, 3, 2, 3, 2, 3, 3, 2, 4, 5, 4, 5, 4, 5, 4, 5, 5, 4, 6, 7, 6, 7, 6, 7, 6, 7, 7, 6, 8, 9, 8, 9, 8, 9, 8, 9, 9, 8, 10, 11, 10, 11, 10, 11, 10, 11, 11, 10, 12, 13, 12, 13, 12, 13, 12, 13, 13, 12, 14, 15, 14, 15, 14, 15, 14, 15, 15, 14, 16, 17, 16, 17, 16, 17, 16, 17, 17, 16, 18, 19, 18, 19, 18, 19, 18, 19, 19, 18, 20, 21, 20, 21, 20, 21, 20, 21, 21, 20, 22, 23, 22, 23, 22, 23, 22, 23, 23, 22, 24, 25, 24, 25, 24, 25, 24, 25, 25, 24, 26, 27, 26, 27, 26, 27, 26, 27, 27, 26, 28, 29, 28, 29, 28, 29, 28, 29, 29, 28, 30, 31, 30, 31, 30, 31, 30, 31, 31, 30, 32, 33, 32, 33, 32, 33, 32, 33, 33, 32, 34, 35, 34, 35, 34, 35, 34, 35, 35, 34, 36, 37, 36, 37, 36, 37, 36, 37, 37, 36, 38, 39, 38, 39, 38, 39, 38, 39, 39, 38};

/* ceq1_v_func:(i0[2],i1[40],i2[180],i3,i4,i5,i6,i7,i8,i9,i10[3x20],i11[20])->(o0[40x220,238nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a8, a9;
  a0=arg[5]? arg[5][0] : 0;
  a1=arg[11]? arg[11][1] : 0;
  a2=arg[2]? arg[2][15] : 0;
  a1=(a1+a2);
  a2=arg[7]? arg[7][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a3=exp(a3);
  a4=(-a3);
  if (res[0]!=0) res[0][0]=a4;
  a4=(a1-a2);
  a4=(a0*a4);
  a4=exp(a4);
  a5=(-a4);
  if (res[0]!=0) res[0][1]=a5;
  a5=arg[11]? arg[11][2] : 0;
  a6=arg[2]? arg[2][24] : 0;
  a5=(a5+a6);
  a6=(a5-a2);
  a6=(a0*a6);
  a6=exp(a6);
  a7=(-a6);
  if (res[0]!=0) res[0][2]=a7;
  a7=(a5-a2);
  a7=(a0*a7);
  a7=exp(a7);
  a8=(-a7);
  if (res[0]!=0) res[0][3]=a8;
  a8=arg[11]? arg[11][3] : 0;
  a9=arg[2]? arg[2][33] : 0;
  a8=(a8+a9);
  a9=(a8-a2);
  a9=(a0*a9);
  a9=exp(a9);
  a10=(-a9);
  if (res[0]!=0) res[0][4]=a10;
  a10=(a8-a2);
  a10=(a0*a10);
  a10=exp(a10);
  a11=(-a10);
  if (res[0]!=0) res[0][5]=a11;
  a11=arg[11]? arg[11][4] : 0;
  a12=arg[2]? arg[2][42] : 0;
  a11=(a11+a12);
  a12=(a11-a2);
  a12=(a0*a12);
  a12=exp(a12);
  a13=(-a12);
  if (res[0]!=0) res[0][6]=a13;
  a13=(a11-a2);
  a13=(a0*a13);
  a13=exp(a13);
  a14=(-a13);
  if (res[0]!=0) res[0][7]=a14;
  a14=arg[11]? arg[11][5] : 0;
  a15=arg[2]? arg[2][51] : 0;
  a14=(a14+a15);
  a15=(a14-a2);
  a15=(a0*a15);
  a15=exp(a15);
  a16=(-a15);
  if (res[0]!=0) res[0][8]=a16;
  a16=(a14-a2);
  a16=(a0*a16);
  a16=exp(a16);
  a17=(-a16);
  if (res[0]!=0) res[0][9]=a17;
  a17=arg[11]? arg[11][6] : 0;
  a18=arg[2]? arg[2][60] : 0;
  a17=(a17+a18);
  a18=(a17-a2);
  a18=(a0*a18);
  a18=exp(a18);
  a19=(-a18);
  if (res[0]!=0) res[0][10]=a19;
  a19=(a17-a2);
  a19=(a0*a19);
  a19=exp(a19);
  a20=(-a19);
  if (res[0]!=0) res[0][11]=a20;
  a20=arg[11]? arg[11][7] : 0;
  a21=arg[2]? arg[2][69] : 0;
  a20=(a20+a21);
  a21=(a20-a2);
  a21=(a0*a21);
  a21=exp(a21);
  a22=(-a21);
  if (res[0]!=0) res[0][12]=a22;
  a22=(a20-a2);
  a22=(a0*a22);
  a22=exp(a22);
  a23=(-a22);
  if (res[0]!=0) res[0][13]=a23;
  a23=arg[11]? arg[11][8] : 0;
  a24=arg[2]? arg[2][78] : 0;
  a23=(a23+a24);
  a24=(a23-a2);
  a24=(a0*a24);
  a24=exp(a24);
  a25=(-a24);
  if (res[0]!=0) res[0][14]=a25;
  a25=(a23-a2);
  a25=(a0*a25);
  a25=exp(a25);
  a26=(-a25);
  if (res[0]!=0) res[0][15]=a26;
  a26=arg[11]? arg[11][9] : 0;
  a27=arg[2]? arg[2][87] : 0;
  a26=(a26+a27);
  a27=(a26-a2);
  a27=(a0*a27);
  a27=exp(a27);
  a28=(-a27);
  if (res[0]!=0) res[0][16]=a28;
  a28=(a26-a2);
  a28=(a0*a28);
  a28=exp(a28);
  a29=(-a28);
  if (res[0]!=0) res[0][17]=a29;
  a29=arg[11]? arg[11][10] : 0;
  a30=arg[2]? arg[2][96] : 0;
  a29=(a29+a30);
  a30=(a29-a2);
  a30=(a0*a30);
  a30=exp(a30);
  a31=(-a30);
  if (res[0]!=0) res[0][18]=a31;
  a31=(a29-a2);
  a31=(a0*a31);
  a31=exp(a31);
  a32=(-a31);
  if (res[0]!=0) res[0][19]=a32;
  a32=arg[11]? arg[11][11] : 0;
  a33=arg[2]? arg[2][105] : 0;
  a32=(a32+a33);
  a33=(a32-a2);
  a33=(a0*a33);
  a33=exp(a33);
  a34=(-a33);
  if (res[0]!=0) res[0][20]=a34;
  a34=(a32-a2);
  a34=(a0*a34);
  a34=exp(a34);
  a35=(-a34);
  if (res[0]!=0) res[0][21]=a35;
  a35=arg[11]? arg[11][12] : 0;
  a36=arg[2]? arg[2][114] : 0;
  a35=(a35+a36);
  a36=(a35-a2);
  a36=(a0*a36);
  a36=exp(a36);
  a37=(-a36);
  if (res[0]!=0) res[0][22]=a37;
  a37=(a35-a2);
  a37=(a0*a37);
  a37=exp(a37);
  a38=(-a37);
  if (res[0]!=0) res[0][23]=a38;
  a38=arg[11]? arg[11][13] : 0;
  a39=arg[2]? arg[2][123] : 0;
  a38=(a38+a39);
  a39=(a38-a2);
  a39=(a0*a39);
  a39=exp(a39);
  a40=(-a39);
  if (res[0]!=0) res[0][24]=a40;
  a40=(a38-a2);
  a40=(a0*a40);
  a40=exp(a40);
  a41=(-a40);
  if (res[0]!=0) res[0][25]=a41;
  a41=arg[11]? arg[11][14] : 0;
  a42=arg[2]? arg[2][132] : 0;
  a41=(a41+a42);
  a42=(a41-a2);
  a42=(a0*a42);
  a42=exp(a42);
  a43=(-a42);
  if (res[0]!=0) res[0][26]=a43;
  a43=(a41-a2);
  a43=(a0*a43);
  a43=exp(a43);
  a44=(-a43);
  if (res[0]!=0) res[0][27]=a44;
  a44=arg[11]? arg[11][15] : 0;
  a45=arg[2]? arg[2][141] : 0;
  a44=(a44+a45);
  a45=(a44-a2);
  a45=(a0*a45);
  a45=exp(a45);
  a46=(-a45);
  if (res[0]!=0) res[0][28]=a46;
  a46=(a44-a2);
  a46=(a0*a46);
  a46=exp(a46);
  a47=(-a46);
  if (res[0]!=0) res[0][29]=a47;
  a47=arg[11]? arg[11][16] : 0;
  a48=arg[2]? arg[2][150] : 0;
  a47=(a47+a48);
  a48=(a47-a2);
  a48=(a0*a48);
  a48=exp(a48);
  a49=(-a48);
  if (res[0]!=0) res[0][30]=a49;
  a49=(a47-a2);
  a49=(a0*a49);
  a49=exp(a49);
  a50=(-a49);
  if (res[0]!=0) res[0][31]=a50;
  a50=arg[11]? arg[11][17] : 0;
  a51=arg[2]? arg[2][159] : 0;
  a50=(a50+a51);
  a51=(a50-a2);
  a51=(a0*a51);
  a51=exp(a51);
  a52=(-a51);
  if (res[0]!=0) res[0][32]=a52;
  a52=(a50-a2);
  a52=(a0*a52);
  a52=exp(a52);
  a53=(-a52);
  if (res[0]!=0) res[0][33]=a53;
  a53=arg[11]? arg[11][18] : 0;
  a54=arg[2]? arg[2][168] : 0;
  a53=(a53+a54);
  a54=(a53-a2);
  a54=(a0*a54);
  a54=exp(a54);
  a55=(-a54);
  if (res[0]!=0) res[0][34]=a55;
  a55=(a53-a2);
  a55=(a0*a55);
  a55=exp(a55);
  a56=(-a55);
  if (res[0]!=0) res[0][35]=a56;
  a56=arg[11]? arg[11][19] : 0;
  a57=arg[2]? arg[2][177] : 0;
  a56=(a56+a57);
  a57=(a56-a2);
  a57=(a0*a57);
  a57=exp(a57);
  a58=(-a57);
  if (res[0]!=0) res[0][36]=a58;
  a58=(a56-a2);
  a58=(a0*a58);
  a58=exp(a58);
  a59=(-a58);
  if (res[0]!=0) res[0][37]=a59;
  a59=-1.;
  a60=arg[11]? arg[11][0] : 0;
  a61=arg[2]? arg[2][6] : 0;
  a60=(a60+a61);
  a61=(a60-a2);
  a61=(a0*a61);
  a61=exp(a61);
  a62=(a59+a61);
  if (res[0]!=0) res[0][38]=a62;
  a62=(a60-a2);
  a62=(a0*a62);
  a62=exp(a62);
  a63=(a59+a62);
  if (res[0]!=0) res[0][39]=a63;
  a63=1.;
  if (res[0]!=0) res[0][40]=a63;
  if (res[0]!=0) res[0][41]=a63;
  if (res[0]!=0) res[0][42]=a63;
  if (res[0]!=0) res[0][43]=a63;
  a64=(a60-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a65=arg[9]? arg[9][0] : 0;
  a66=arg[2]? arg[2][8] : 0;
  a66=(a65*a66);
  a67=arg[3]? arg[3][0] : 0;
  a68=arg[4]? arg[4][0] : 0;
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a70=arg[0]? arg[0][0] : 0;
  a71=arg[2]? arg[2][0] : 0;
  a70=(a70-a71);
  a61=(a61*a70);
  a61=(a0*a61);
  a66=(a66-a61);
  a61=(a0*a60);
  a61=exp(a61);
  a70=arg[10]? arg[10][0] : 0;
  a71=(a0*a2);
  a71=(-a71);
  a71=exp(a71);
  a70=(a70*a71);
  a61=(a61*a70);
  a61=(a0*a61);
  a66=(a66-a61);
  if (res[0]!=0) res[0][44]=a66;
  a66=(a60-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a61=arg[8]? arg[8][0] : 0;
  a70=arg[2]? arg[2][7] : 0;
  a70=(a61*a70);
  a71=(a67*a68);
  a70=(a70/a71);
  a70=(a66*a70);
  a70=(a0*a70);
  a72=arg[0]? arg[0][1] : 0;
  a73=arg[2]? arg[2][1] : 0;
  a72=(a72-a73);
  a62=(a62*a72);
  a62=(a0*a62);
  a70=(a70-a62);
  a60=(a0*a60);
  a60=exp(a60);
  a62=arg[10]? arg[10][1] : 0;
  a72=(a0*a2);
  a72=(-a72);
  a72=exp(a72);
  a62=(a62*a72);
  a60=(a60*a62);
  a60=(a0*a60);
  a70=(a70-a60);
  if (res[0]!=0) res[0][45]=a70;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][46]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][47]=a64;
  a64=(a59+a3);
  if (res[0]!=0) res[0][48]=a64;
  a64=(a59+a4);
  if (res[0]!=0) res[0][49]=a64;
  if (res[0]!=0) res[0][50]=a63;
  if (res[0]!=0) res[0][51]=a63;
  if (res[0]!=0) res[0][52]=a63;
  if (res[0]!=0) res[0][53]=a63;
  a64=(a1-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][17] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][0] : 0;
  a70=arg[2]? arg[2][9] : 0;
  a71=(a71-a70);
  a3=(a3*a71);
  a3=(a0*a3);
  a69=(a69-a3);
  a3=(a0*a1);
  a3=exp(a3);
  a71=arg[10]? arg[10][3] : 0;
  a70=(a0*a2);
  a70=(-a70);
  a70=exp(a70);
  a71=(a71*a70);
  a3=(a3*a71);
  a3=(a0*a3);
  a69=(a69-a3);
  if (res[0]!=0) res[0][54]=a69;
  a69=(a1-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a3=arg[2]? arg[2][16] : 0;
  a3=(a61*a3);
  a71=(a67*a68);
  a3=(a3/a71);
  a3=(a69*a3);
  a3=(a0*a3);
  a70=arg[1]? arg[1][1] : 0;
  a60=arg[2]? arg[2][10] : 0;
  a70=(a70-a60);
  a4=(a4*a70);
  a4=(a0*a4);
  a3=(a3-a4);
  a1=(a0*a1);
  a1=exp(a1);
  a4=arg[10]? arg[10][4] : 0;
  a70=(a0*a2);
  a70=(-a70);
  a70=exp(a70);
  a4=(a4*a70);
  a1=(a1*a4);
  a1=(a0*a1);
  a3=(a3-a1);
  if (res[0]!=0) res[0][55]=a3;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][56]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][57]=a64;
  a64=(a59+a6);
  if (res[0]!=0) res[0][58]=a64;
  a64=(a59+a7);
  if (res[0]!=0) res[0][59]=a64;
  if (res[0]!=0) res[0][60]=a63;
  if (res[0]!=0) res[0][61]=a63;
  if (res[0]!=0) res[0][62]=a63;
  if (res[0]!=0) res[0][63]=a63;
  a64=(a5-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][26] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][2] : 0;
  a3=arg[2]? arg[2][18] : 0;
  a71=(a71-a3);
  a6=(a6*a71);
  a6=(a0*a6);
  a66=(a66-a6);
  a6=(a0*a5);
  a6=exp(a6);
  a71=arg[10]? arg[10][6] : 0;
  a3=(a0*a2);
  a3=(-a3);
  a3=exp(a3);
  a71=(a71*a3);
  a6=(a6*a71);
  a6=(a0*a6);
  a66=(a66-a6);
  if (res[0]!=0) res[0][64]=a66;
  a66=(a5-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a6=arg[2]? arg[2][25] : 0;
  a6=(a61*a6);
  a71=(a67*a68);
  a6=(a6/a71);
  a6=(a66*a6);
  a6=(a0*a6);
  a3=arg[1]? arg[1][3] : 0;
  a1=arg[2]? arg[2][19] : 0;
  a3=(a3-a1);
  a7=(a7*a3);
  a7=(a0*a7);
  a6=(a6-a7);
  a5=(a0*a5);
  a5=exp(a5);
  a7=arg[10]? arg[10][7] : 0;
  a3=(a0*a2);
  a3=(-a3);
  a3=exp(a3);
  a7=(a7*a3);
  a5=(a5*a7);
  a5=(a0*a5);
  a6=(a6-a5);
  if (res[0]!=0) res[0][65]=a6;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][66]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][67]=a64;
  a64=(a59+a9);
  if (res[0]!=0) res[0][68]=a64;
  a64=(a59+a10);
  if (res[0]!=0) res[0][69]=a64;
  if (res[0]!=0) res[0][70]=a63;
  if (res[0]!=0) res[0][71]=a63;
  if (res[0]!=0) res[0][72]=a63;
  if (res[0]!=0) res[0][73]=a63;
  a64=(a8-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][35] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][4] : 0;
  a6=arg[2]? arg[2][27] : 0;
  a71=(a71-a6);
  a9=(a9*a71);
  a9=(a0*a9);
  a69=(a69-a9);
  a9=(a0*a8);
  a9=exp(a9);
  a71=arg[10]? arg[10][9] : 0;
  a6=(a0*a2);
  a6=(-a6);
  a6=exp(a6);
  a71=(a71*a6);
  a9=(a9*a71);
  a9=(a0*a9);
  a69=(a69-a9);
  if (res[0]!=0) res[0][74]=a69;
  a69=(a8-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a9=arg[2]? arg[2][34] : 0;
  a9=(a61*a9);
  a71=(a67*a68);
  a9=(a9/a71);
  a9=(a69*a9);
  a9=(a0*a9);
  a6=arg[1]? arg[1][5] : 0;
  a5=arg[2]? arg[2][28] : 0;
  a6=(a6-a5);
  a10=(a10*a6);
  a10=(a0*a10);
  a9=(a9-a10);
  a8=(a0*a8);
  a8=exp(a8);
  a10=arg[10]? arg[10][10] : 0;
  a6=(a0*a2);
  a6=(-a6);
  a6=exp(a6);
  a10=(a10*a6);
  a8=(a8*a10);
  a8=(a0*a8);
  a9=(a9-a8);
  if (res[0]!=0) res[0][75]=a9;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][76]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][77]=a64;
  a64=(a59+a12);
  if (res[0]!=0) res[0][78]=a64;
  a64=(a59+a13);
  if (res[0]!=0) res[0][79]=a64;
  if (res[0]!=0) res[0][80]=a63;
  if (res[0]!=0) res[0][81]=a63;
  if (res[0]!=0) res[0][82]=a63;
  if (res[0]!=0) res[0][83]=a63;
  a64=(a11-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][44] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][6] : 0;
  a9=arg[2]? arg[2][36] : 0;
  a71=(a71-a9);
  a12=(a12*a71);
  a12=(a0*a12);
  a66=(a66-a12);
  a12=(a0*a11);
  a12=exp(a12);
  a71=arg[10]? arg[10][12] : 0;
  a9=(a0*a2);
  a9=(-a9);
  a9=exp(a9);
  a71=(a71*a9);
  a12=(a12*a71);
  a12=(a0*a12);
  a66=(a66-a12);
  if (res[0]!=0) res[0][84]=a66;
  a66=(a11-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a12=arg[2]? arg[2][43] : 0;
  a12=(a61*a12);
  a71=(a67*a68);
  a12=(a12/a71);
  a12=(a66*a12);
  a12=(a0*a12);
  a9=arg[1]? arg[1][7] : 0;
  a8=arg[2]? arg[2][37] : 0;
  a9=(a9-a8);
  a13=(a13*a9);
  a13=(a0*a13);
  a12=(a12-a13);
  a11=(a0*a11);
  a11=exp(a11);
  a13=arg[10]? arg[10][13] : 0;
  a9=(a0*a2);
  a9=(-a9);
  a9=exp(a9);
  a13=(a13*a9);
  a11=(a11*a13);
  a11=(a0*a11);
  a12=(a12-a11);
  if (res[0]!=0) res[0][85]=a12;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][86]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][87]=a64;
  a64=(a59+a15);
  if (res[0]!=0) res[0][88]=a64;
  a64=(a59+a16);
  if (res[0]!=0) res[0][89]=a64;
  if (res[0]!=0) res[0][90]=a63;
  if (res[0]!=0) res[0][91]=a63;
  if (res[0]!=0) res[0][92]=a63;
  if (res[0]!=0) res[0][93]=a63;
  a64=(a14-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][53] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][8] : 0;
  a12=arg[2]? arg[2][45] : 0;
  a71=(a71-a12);
  a15=(a15*a71);
  a15=(a0*a15);
  a69=(a69-a15);
  a15=(a0*a14);
  a15=exp(a15);
  a71=arg[10]? arg[10][15] : 0;
  a12=(a0*a2);
  a12=(-a12);
  a12=exp(a12);
  a71=(a71*a12);
  a15=(a15*a71);
  a15=(a0*a15);
  a69=(a69-a15);
  if (res[0]!=0) res[0][94]=a69;
  a69=(a14-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a15=arg[2]? arg[2][52] : 0;
  a15=(a61*a15);
  a71=(a67*a68);
  a15=(a15/a71);
  a15=(a69*a15);
  a15=(a0*a15);
  a12=arg[1]? arg[1][9] : 0;
  a11=arg[2]? arg[2][46] : 0;
  a12=(a12-a11);
  a16=(a16*a12);
  a16=(a0*a16);
  a15=(a15-a16);
  a14=(a0*a14);
  a14=exp(a14);
  a16=arg[10]? arg[10][16] : 0;
  a12=(a0*a2);
  a12=(-a12);
  a12=exp(a12);
  a16=(a16*a12);
  a14=(a14*a16);
  a14=(a0*a14);
  a15=(a15-a14);
  if (res[0]!=0) res[0][95]=a15;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][96]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][97]=a64;
  a64=(a59+a18);
  if (res[0]!=0) res[0][98]=a64;
  a64=(a59+a19);
  if (res[0]!=0) res[0][99]=a64;
  if (res[0]!=0) res[0][100]=a63;
  if (res[0]!=0) res[0][101]=a63;
  if (res[0]!=0) res[0][102]=a63;
  if (res[0]!=0) res[0][103]=a63;
  a64=(a17-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][62] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][10] : 0;
  a15=arg[2]? arg[2][54] : 0;
  a71=(a71-a15);
  a18=(a18*a71);
  a18=(a0*a18);
  a66=(a66-a18);
  a18=(a0*a17);
  a18=exp(a18);
  a71=arg[10]? arg[10][18] : 0;
  a15=(a0*a2);
  a15=(-a15);
  a15=exp(a15);
  a71=(a71*a15);
  a18=(a18*a71);
  a18=(a0*a18);
  a66=(a66-a18);
  if (res[0]!=0) res[0][104]=a66;
  a66=(a17-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a18=arg[2]? arg[2][61] : 0;
  a18=(a61*a18);
  a71=(a67*a68);
  a18=(a18/a71);
  a18=(a66*a18);
  a18=(a0*a18);
  a15=arg[1]? arg[1][11] : 0;
  a14=arg[2]? arg[2][55] : 0;
  a15=(a15-a14);
  a19=(a19*a15);
  a19=(a0*a19);
  a18=(a18-a19);
  a17=(a0*a17);
  a17=exp(a17);
  a19=arg[10]? arg[10][19] : 0;
  a15=(a0*a2);
  a15=(-a15);
  a15=exp(a15);
  a19=(a19*a15);
  a17=(a17*a19);
  a17=(a0*a17);
  a18=(a18-a17);
  if (res[0]!=0) res[0][105]=a18;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][106]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][107]=a64;
  a64=(a59+a21);
  if (res[0]!=0) res[0][108]=a64;
  a64=(a59+a22);
  if (res[0]!=0) res[0][109]=a64;
  if (res[0]!=0) res[0][110]=a63;
  if (res[0]!=0) res[0][111]=a63;
  if (res[0]!=0) res[0][112]=a63;
  if (res[0]!=0) res[0][113]=a63;
  a64=(a20-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][71] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][12] : 0;
  a18=arg[2]? arg[2][63] : 0;
  a71=(a71-a18);
  a21=(a21*a71);
  a21=(a0*a21);
  a69=(a69-a21);
  a21=(a0*a20);
  a21=exp(a21);
  a71=arg[10]? arg[10][21] : 0;
  a18=(a0*a2);
  a18=(-a18);
  a18=exp(a18);
  a71=(a71*a18);
  a21=(a21*a71);
  a21=(a0*a21);
  a69=(a69-a21);
  if (res[0]!=0) res[0][114]=a69;
  a69=(a20-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a21=arg[2]? arg[2][70] : 0;
  a21=(a61*a21);
  a71=(a67*a68);
  a21=(a21/a71);
  a21=(a69*a21);
  a21=(a0*a21);
  a18=arg[1]? arg[1][13] : 0;
  a17=arg[2]? arg[2][64] : 0;
  a18=(a18-a17);
  a22=(a22*a18);
  a22=(a0*a22);
  a21=(a21-a22);
  a20=(a0*a20);
  a20=exp(a20);
  a22=arg[10]? arg[10][22] : 0;
  a18=(a0*a2);
  a18=(-a18);
  a18=exp(a18);
  a22=(a22*a18);
  a20=(a20*a22);
  a20=(a0*a20);
  a21=(a21-a20);
  if (res[0]!=0) res[0][115]=a21;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][116]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][117]=a64;
  a64=(a59+a24);
  if (res[0]!=0) res[0][118]=a64;
  a64=(a59+a25);
  if (res[0]!=0) res[0][119]=a64;
  if (res[0]!=0) res[0][120]=a63;
  if (res[0]!=0) res[0][121]=a63;
  if (res[0]!=0) res[0][122]=a63;
  if (res[0]!=0) res[0][123]=a63;
  a64=(a23-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][80] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][14] : 0;
  a21=arg[2]? arg[2][72] : 0;
  a71=(a71-a21);
  a24=(a24*a71);
  a24=(a0*a24);
  a66=(a66-a24);
  a24=(a0*a23);
  a24=exp(a24);
  a71=arg[10]? arg[10][24] : 0;
  a21=(a0*a2);
  a21=(-a21);
  a21=exp(a21);
  a71=(a71*a21);
  a24=(a24*a71);
  a24=(a0*a24);
  a66=(a66-a24);
  if (res[0]!=0) res[0][124]=a66;
  a66=(a23-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a24=arg[2]? arg[2][79] : 0;
  a24=(a61*a24);
  a71=(a67*a68);
  a24=(a24/a71);
  a24=(a66*a24);
  a24=(a0*a24);
  a21=arg[1]? arg[1][15] : 0;
  a20=arg[2]? arg[2][73] : 0;
  a21=(a21-a20);
  a25=(a25*a21);
  a25=(a0*a25);
  a24=(a24-a25);
  a23=(a0*a23);
  a23=exp(a23);
  a25=arg[10]? arg[10][25] : 0;
  a21=(a0*a2);
  a21=(-a21);
  a21=exp(a21);
  a25=(a25*a21);
  a23=(a23*a25);
  a23=(a0*a23);
  a24=(a24-a23);
  if (res[0]!=0) res[0][125]=a24;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][126]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][127]=a64;
  a64=(a59+a27);
  if (res[0]!=0) res[0][128]=a64;
  a64=(a59+a28);
  if (res[0]!=0) res[0][129]=a64;
  if (res[0]!=0) res[0][130]=a63;
  if (res[0]!=0) res[0][131]=a63;
  if (res[0]!=0) res[0][132]=a63;
  if (res[0]!=0) res[0][133]=a63;
  a64=(a26-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][89] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][16] : 0;
  a24=arg[2]? arg[2][81] : 0;
  a71=(a71-a24);
  a27=(a27*a71);
  a27=(a0*a27);
  a69=(a69-a27);
  a27=(a0*a26);
  a27=exp(a27);
  a71=arg[10]? arg[10][27] : 0;
  a24=(a0*a2);
  a24=(-a24);
  a24=exp(a24);
  a71=(a71*a24);
  a27=(a27*a71);
  a27=(a0*a27);
  a69=(a69-a27);
  if (res[0]!=0) res[0][134]=a69;
  a69=(a26-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a27=arg[2]? arg[2][88] : 0;
  a27=(a61*a27);
  a71=(a67*a68);
  a27=(a27/a71);
  a27=(a69*a27);
  a27=(a0*a27);
  a24=arg[1]? arg[1][17] : 0;
  a23=arg[2]? arg[2][82] : 0;
  a24=(a24-a23);
  a28=(a28*a24);
  a28=(a0*a28);
  a27=(a27-a28);
  a26=(a0*a26);
  a26=exp(a26);
  a28=arg[10]? arg[10][28] : 0;
  a24=(a0*a2);
  a24=(-a24);
  a24=exp(a24);
  a28=(a28*a24);
  a26=(a26*a28);
  a26=(a0*a26);
  a27=(a27-a26);
  if (res[0]!=0) res[0][135]=a27;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][136]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][137]=a64;
  a64=(a59+a30);
  if (res[0]!=0) res[0][138]=a64;
  a64=(a59+a31);
  if (res[0]!=0) res[0][139]=a64;
  if (res[0]!=0) res[0][140]=a63;
  if (res[0]!=0) res[0][141]=a63;
  if (res[0]!=0) res[0][142]=a63;
  if (res[0]!=0) res[0][143]=a63;
  a64=(a29-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][98] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][18] : 0;
  a27=arg[2]? arg[2][90] : 0;
  a71=(a71-a27);
  a30=(a30*a71);
  a30=(a0*a30);
  a66=(a66-a30);
  a30=(a0*a29);
  a30=exp(a30);
  a71=arg[10]? arg[10][30] : 0;
  a27=(a0*a2);
  a27=(-a27);
  a27=exp(a27);
  a71=(a71*a27);
  a30=(a30*a71);
  a30=(a0*a30);
  a66=(a66-a30);
  if (res[0]!=0) res[0][144]=a66;
  a66=(a29-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a30=arg[2]? arg[2][97] : 0;
  a30=(a61*a30);
  a71=(a67*a68);
  a30=(a30/a71);
  a30=(a66*a30);
  a30=(a0*a30);
  a27=arg[1]? arg[1][19] : 0;
  a26=arg[2]? arg[2][91] : 0;
  a27=(a27-a26);
  a31=(a31*a27);
  a31=(a0*a31);
  a30=(a30-a31);
  a29=(a0*a29);
  a29=exp(a29);
  a31=arg[10]? arg[10][31] : 0;
  a27=(a0*a2);
  a27=(-a27);
  a27=exp(a27);
  a31=(a31*a27);
  a29=(a29*a31);
  a29=(a0*a29);
  a30=(a30-a29);
  if (res[0]!=0) res[0][145]=a30;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][146]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][147]=a64;
  a64=(a59+a33);
  if (res[0]!=0) res[0][148]=a64;
  a64=(a59+a34);
  if (res[0]!=0) res[0][149]=a64;
  if (res[0]!=0) res[0][150]=a63;
  if (res[0]!=0) res[0][151]=a63;
  if (res[0]!=0) res[0][152]=a63;
  if (res[0]!=0) res[0][153]=a63;
  a64=(a32-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][107] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][20] : 0;
  a30=arg[2]? arg[2][99] : 0;
  a71=(a71-a30);
  a33=(a33*a71);
  a33=(a0*a33);
  a69=(a69-a33);
  a33=(a0*a32);
  a33=exp(a33);
  a71=arg[10]? arg[10][33] : 0;
  a30=(a0*a2);
  a30=(-a30);
  a30=exp(a30);
  a71=(a71*a30);
  a33=(a33*a71);
  a33=(a0*a33);
  a69=(a69-a33);
  if (res[0]!=0) res[0][154]=a69;
  a69=(a32-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a33=arg[2]? arg[2][106] : 0;
  a33=(a61*a33);
  a71=(a67*a68);
  a33=(a33/a71);
  a33=(a69*a33);
  a33=(a0*a33);
  a30=arg[1]? arg[1][21] : 0;
  a29=arg[2]? arg[2][100] : 0;
  a30=(a30-a29);
  a34=(a34*a30);
  a34=(a0*a34);
  a33=(a33-a34);
  a32=(a0*a32);
  a32=exp(a32);
  a34=arg[10]? arg[10][34] : 0;
  a30=(a0*a2);
  a30=(-a30);
  a30=exp(a30);
  a34=(a34*a30);
  a32=(a32*a34);
  a32=(a0*a32);
  a33=(a33-a32);
  if (res[0]!=0) res[0][155]=a33;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][156]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][157]=a64;
  a64=(a59+a36);
  if (res[0]!=0) res[0][158]=a64;
  a64=(a59+a37);
  if (res[0]!=0) res[0][159]=a64;
  if (res[0]!=0) res[0][160]=a63;
  if (res[0]!=0) res[0][161]=a63;
  if (res[0]!=0) res[0][162]=a63;
  if (res[0]!=0) res[0][163]=a63;
  a64=(a35-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][116] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][22] : 0;
  a33=arg[2]? arg[2][108] : 0;
  a71=(a71-a33);
  a36=(a36*a71);
  a36=(a0*a36);
  a66=(a66-a36);
  a36=(a0*a35);
  a36=exp(a36);
  a71=arg[10]? arg[10][36] : 0;
  a33=(a0*a2);
  a33=(-a33);
  a33=exp(a33);
  a71=(a71*a33);
  a36=(a36*a71);
  a36=(a0*a36);
  a66=(a66-a36);
  if (res[0]!=0) res[0][164]=a66;
  a66=(a35-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a36=arg[2]? arg[2][115] : 0;
  a36=(a61*a36);
  a71=(a67*a68);
  a36=(a36/a71);
  a36=(a66*a36);
  a36=(a0*a36);
  a33=arg[1]? arg[1][23] : 0;
  a32=arg[2]? arg[2][109] : 0;
  a33=(a33-a32);
  a37=(a37*a33);
  a37=(a0*a37);
  a36=(a36-a37);
  a35=(a0*a35);
  a35=exp(a35);
  a37=arg[10]? arg[10][37] : 0;
  a33=(a0*a2);
  a33=(-a33);
  a33=exp(a33);
  a37=(a37*a33);
  a35=(a35*a37);
  a35=(a0*a35);
  a36=(a36-a35);
  if (res[0]!=0) res[0][165]=a36;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][166]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][167]=a64;
  a64=(a59+a39);
  if (res[0]!=0) res[0][168]=a64;
  a64=(a59+a40);
  if (res[0]!=0) res[0][169]=a64;
  if (res[0]!=0) res[0][170]=a63;
  if (res[0]!=0) res[0][171]=a63;
  if (res[0]!=0) res[0][172]=a63;
  if (res[0]!=0) res[0][173]=a63;
  a64=(a38-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][125] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][24] : 0;
  a36=arg[2]? arg[2][117] : 0;
  a71=(a71-a36);
  a39=(a39*a71);
  a39=(a0*a39);
  a69=(a69-a39);
  a39=(a0*a38);
  a39=exp(a39);
  a71=arg[10]? arg[10][39] : 0;
  a36=(a0*a2);
  a36=(-a36);
  a36=exp(a36);
  a71=(a71*a36);
  a39=(a39*a71);
  a39=(a0*a39);
  a69=(a69-a39);
  if (res[0]!=0) res[0][174]=a69;
  a69=(a38-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a39=arg[2]? arg[2][124] : 0;
  a39=(a61*a39);
  a71=(a67*a68);
  a39=(a39/a71);
  a39=(a69*a39);
  a39=(a0*a39);
  a36=arg[1]? arg[1][25] : 0;
  a35=arg[2]? arg[2][118] : 0;
  a36=(a36-a35);
  a40=(a40*a36);
  a40=(a0*a40);
  a39=(a39-a40);
  a38=(a0*a38);
  a38=exp(a38);
  a40=arg[10]? arg[10][40] : 0;
  a36=(a0*a2);
  a36=(-a36);
  a36=exp(a36);
  a40=(a40*a36);
  a38=(a38*a40);
  a38=(a0*a38);
  a39=(a39-a38);
  if (res[0]!=0) res[0][175]=a39;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][176]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][177]=a64;
  a64=(a59+a42);
  if (res[0]!=0) res[0][178]=a64;
  a64=(a59+a43);
  if (res[0]!=0) res[0][179]=a64;
  if (res[0]!=0) res[0][180]=a63;
  if (res[0]!=0) res[0][181]=a63;
  if (res[0]!=0) res[0][182]=a63;
  if (res[0]!=0) res[0][183]=a63;
  a64=(a41-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][134] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][26] : 0;
  a39=arg[2]? arg[2][126] : 0;
  a71=(a71-a39);
  a42=(a42*a71);
  a42=(a0*a42);
  a66=(a66-a42);
  a42=(a0*a41);
  a42=exp(a42);
  a71=arg[10]? arg[10][42] : 0;
  a39=(a0*a2);
  a39=(-a39);
  a39=exp(a39);
  a71=(a71*a39);
  a42=(a42*a71);
  a42=(a0*a42);
  a66=(a66-a42);
  if (res[0]!=0) res[0][184]=a66;
  a66=(a41-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a42=arg[2]? arg[2][133] : 0;
  a42=(a61*a42);
  a71=(a67*a68);
  a42=(a42/a71);
  a42=(a66*a42);
  a42=(a0*a42);
  a39=arg[1]? arg[1][27] : 0;
  a38=arg[2]? arg[2][127] : 0;
  a39=(a39-a38);
  a43=(a43*a39);
  a43=(a0*a43);
  a42=(a42-a43);
  a41=(a0*a41);
  a41=exp(a41);
  a43=arg[10]? arg[10][43] : 0;
  a39=(a0*a2);
  a39=(-a39);
  a39=exp(a39);
  a43=(a43*a39);
  a41=(a41*a43);
  a41=(a0*a41);
  a42=(a42-a41);
  if (res[0]!=0) res[0][185]=a42;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][186]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][187]=a64;
  a64=(a59+a45);
  if (res[0]!=0) res[0][188]=a64;
  a64=(a59+a46);
  if (res[0]!=0) res[0][189]=a64;
  if (res[0]!=0) res[0][190]=a63;
  if (res[0]!=0) res[0][191]=a63;
  if (res[0]!=0) res[0][192]=a63;
  if (res[0]!=0) res[0][193]=a63;
  a64=(a44-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][143] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][28] : 0;
  a42=arg[2]? arg[2][135] : 0;
  a71=(a71-a42);
  a45=(a45*a71);
  a45=(a0*a45);
  a69=(a69-a45);
  a45=(a0*a44);
  a45=exp(a45);
  a71=arg[10]? arg[10][45] : 0;
  a42=(a0*a2);
  a42=(-a42);
  a42=exp(a42);
  a71=(a71*a42);
  a45=(a45*a71);
  a45=(a0*a45);
  a69=(a69-a45);
  if (res[0]!=0) res[0][194]=a69;
  a69=(a44-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a45=arg[2]? arg[2][142] : 0;
  a45=(a61*a45);
  a71=(a67*a68);
  a45=(a45/a71);
  a45=(a69*a45);
  a45=(a0*a45);
  a42=arg[1]? arg[1][29] : 0;
  a41=arg[2]? arg[2][136] : 0;
  a42=(a42-a41);
  a46=(a46*a42);
  a46=(a0*a46);
  a45=(a45-a46);
  a44=(a0*a44);
  a44=exp(a44);
  a46=arg[10]? arg[10][46] : 0;
  a42=(a0*a2);
  a42=(-a42);
  a42=exp(a42);
  a46=(a46*a42);
  a44=(a44*a46);
  a44=(a0*a44);
  a45=(a45-a44);
  if (res[0]!=0) res[0][195]=a45;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][196]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][197]=a64;
  a64=(a59+a48);
  if (res[0]!=0) res[0][198]=a64;
  a64=(a59+a49);
  if (res[0]!=0) res[0][199]=a64;
  if (res[0]!=0) res[0][200]=a63;
  if (res[0]!=0) res[0][201]=a63;
  if (res[0]!=0) res[0][202]=a63;
  if (res[0]!=0) res[0][203]=a63;
  a64=(a47-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][152] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][30] : 0;
  a45=arg[2]? arg[2][144] : 0;
  a71=(a71-a45);
  a48=(a48*a71);
  a48=(a0*a48);
  a66=(a66-a48);
  a48=(a0*a47);
  a48=exp(a48);
  a71=arg[10]? arg[10][48] : 0;
  a45=(a0*a2);
  a45=(-a45);
  a45=exp(a45);
  a71=(a71*a45);
  a48=(a48*a71);
  a48=(a0*a48);
  a66=(a66-a48);
  if (res[0]!=0) res[0][204]=a66;
  a66=(a47-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a48=arg[2]? arg[2][151] : 0;
  a48=(a61*a48);
  a71=(a67*a68);
  a48=(a48/a71);
  a48=(a66*a48);
  a48=(a0*a48);
  a45=arg[1]? arg[1][31] : 0;
  a44=arg[2]? arg[2][145] : 0;
  a45=(a45-a44);
  a49=(a49*a45);
  a49=(a0*a49);
  a48=(a48-a49);
  a47=(a0*a47);
  a47=exp(a47);
  a49=arg[10]? arg[10][49] : 0;
  a45=(a0*a2);
  a45=(-a45);
  a45=exp(a45);
  a49=(a49*a45);
  a47=(a47*a49);
  a47=(a0*a47);
  a48=(a48-a47);
  if (res[0]!=0) res[0][205]=a48;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][206]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][207]=a64;
  a64=(a59+a51);
  if (res[0]!=0) res[0][208]=a64;
  a64=(a59+a52);
  if (res[0]!=0) res[0][209]=a64;
  if (res[0]!=0) res[0][210]=a63;
  if (res[0]!=0) res[0][211]=a63;
  if (res[0]!=0) res[0][212]=a63;
  if (res[0]!=0) res[0][213]=a63;
  a64=(a50-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a69=arg[2]? arg[2][161] : 0;
  a69=(a65*a69);
  a66=(a67*a68);
  a69=(a69/a66);
  a69=(a64*a69);
  a69=(a0*a69);
  a71=arg[1]? arg[1][32] : 0;
  a48=arg[2]? arg[2][153] : 0;
  a71=(a71-a48);
  a51=(a51*a71);
  a51=(a0*a51);
  a69=(a69-a51);
  a51=(a0*a50);
  a51=exp(a51);
  a71=arg[10]? arg[10][51] : 0;
  a48=(a0*a2);
  a48=(-a48);
  a48=exp(a48);
  a71=(a71*a48);
  a51=(a51*a71);
  a51=(a0*a51);
  a69=(a69-a51);
  if (res[0]!=0) res[0][214]=a69;
  a69=(a50-a2);
  a69=(a0*a69);
  a69=exp(a69);
  a51=arg[2]? arg[2][160] : 0;
  a51=(a61*a51);
  a71=(a67*a68);
  a51=(a51/a71);
  a51=(a69*a51);
  a51=(a0*a51);
  a48=arg[1]? arg[1][33] : 0;
  a47=arg[2]? arg[2][154] : 0;
  a48=(a48-a47);
  a52=(a52*a48);
  a52=(a0*a52);
  a51=(a51-a52);
  a50=(a0*a50);
  a50=exp(a50);
  a52=arg[10]? arg[10][52] : 0;
  a48=(a0*a2);
  a48=(-a48);
  a48=exp(a48);
  a52=(a52*a48);
  a50=(a50*a52);
  a50=(a0*a50);
  a51=(a51-a50);
  if (res[0]!=0) res[0][215]=a51;
  a69=(a63-a69);
  a69=(a69/a71);
  a69=(a61*a69);
  a69=(-a69);
  if (res[0]!=0) res[0][216]=a69;
  a64=(a63-a64);
  a64=(a64/a66);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][217]=a64;
  a64=(a59+a54);
  if (res[0]!=0) res[0][218]=a64;
  a64=(a59+a55);
  if (res[0]!=0) res[0][219]=a64;
  if (res[0]!=0) res[0][220]=a63;
  if (res[0]!=0) res[0][221]=a63;
  if (res[0]!=0) res[0][222]=a63;
  if (res[0]!=0) res[0][223]=a63;
  a64=(a53-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a66=arg[2]? arg[2][170] : 0;
  a66=(a65*a66);
  a69=(a67*a68);
  a66=(a66/a69);
  a66=(a64*a66);
  a66=(a0*a66);
  a71=arg[1]? arg[1][34] : 0;
  a51=arg[2]? arg[2][162] : 0;
  a71=(a71-a51);
  a54=(a54*a71);
  a54=(a0*a54);
  a66=(a66-a54);
  a54=(a0*a53);
  a54=exp(a54);
  a71=arg[10]? arg[10][54] : 0;
  a51=(a0*a2);
  a51=(-a51);
  a51=exp(a51);
  a71=(a71*a51);
  a54=(a54*a71);
  a54=(a0*a54);
  a66=(a66-a54);
  if (res[0]!=0) res[0][224]=a66;
  a66=(a53-a2);
  a66=(a0*a66);
  a66=exp(a66);
  a54=arg[2]? arg[2][169] : 0;
  a54=(a61*a54);
  a71=(a67*a68);
  a54=(a54/a71);
  a54=(a66*a54);
  a54=(a0*a54);
  a51=arg[1]? arg[1][35] : 0;
  a50=arg[2]? arg[2][163] : 0;
  a51=(a51-a50);
  a55=(a55*a51);
  a55=(a0*a55);
  a54=(a54-a55);
  a53=(a0*a53);
  a53=exp(a53);
  a55=arg[10]? arg[10][55] : 0;
  a51=(a0*a2);
  a51=(-a51);
  a51=exp(a51);
  a55=(a55*a51);
  a53=(a53*a55);
  a53=(a0*a53);
  a54=(a54-a53);
  if (res[0]!=0) res[0][225]=a54;
  a66=(a63-a66);
  a66=(a66/a71);
  a66=(a61*a66);
  a66=(-a66);
  if (res[0]!=0) res[0][226]=a66;
  a64=(a63-a64);
  a64=(a64/a69);
  a64=(a65*a64);
  a64=(-a64);
  if (res[0]!=0) res[0][227]=a64;
  a64=(a59+a57);
  if (res[0]!=0) res[0][228]=a64;
  a59=(a59+a58);
  if (res[0]!=0) res[0][229]=a59;
  if (res[0]!=0) res[0][230]=a63;
  if (res[0]!=0) res[0][231]=a63;
  if (res[0]!=0) res[0][232]=a63;
  if (res[0]!=0) res[0][233]=a63;
  a59=(a56-a2);
  a59=(a0*a59);
  a59=exp(a59);
  a64=arg[2]? arg[2][179] : 0;
  a64=(a65*a64);
  a69=(a67*a68);
  a64=(a64/a69);
  a64=(a59*a64);
  a64=(a0*a64);
  a66=arg[1]? arg[1][36] : 0;
  a71=arg[2]? arg[2][171] : 0;
  a66=(a66-a71);
  a57=(a57*a66);
  a57=(a0*a57);
  a64=(a64-a57);
  a57=(a0*a56);
  a57=exp(a57);
  a66=arg[10]? arg[10][57] : 0;
  a71=(a0*a2);
  a71=(-a71);
  a71=exp(a71);
  a66=(a66*a71);
  a57=(a57*a66);
  a57=(a0*a57);
  a64=(a64-a57);
  if (res[0]!=0) res[0][234]=a64;
  a64=(a56-a2);
  a64=(a0*a64);
  a64=exp(a64);
  a57=arg[2]? arg[2][178] : 0;
  a57=(a61*a57);
  a67=(a67*a68);
  a57=(a57/a67);
  a57=(a64*a57);
  a57=(a0*a57);
  a68=arg[1]? arg[1][37] : 0;
  a66=arg[2]? arg[2][172] : 0;
  a68=(a68-a66);
  a58=(a58*a68);
  a58=(a0*a58);
  a57=(a57-a58);
  a56=(a0*a56);
  a56=exp(a56);
  a58=arg[10]? arg[10][58] : 0;
  a2=(a0*a2);
  a2=(-a2);
  a2=exp(a2);
  a58=(a58*a2);
  a56=(a56*a58);
  a0=(a0*a56);
  a57=(a57-a0);
  if (res[0]!=0) res[0][235]=a57;
  a64=(a63-a64);
  a64=(a64/a67);
  a61=(a61*a64);
  a61=(-a61);
  if (res[0]!=0) res[0][236]=a61;
  a63=(a63-a59);
  a63=(a63/a69);
  a65=(a65*a63);
  a65=(-a65);
  if (res[0]!=0) res[0][237]=a65;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ceq1_v_func_n_in(void) { return 12;}

CASADI_SYMBOL_EXPORT casadi_int ceq1_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ceq1_v_func_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_v_func_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    case 9: return "i9";
    case 10: return "i10";
    case 11: return "i11";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_v_func_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s3;
    case 5: return casadi_s3;
    case 6: return casadi_s3;
    case 7: return casadi_s3;
    case 8: return casadi_s3;
    case 9: return casadi_s3;
    case 10: return casadi_s4;
    case 11: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_ceq1_v_func(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[727];
  casadi_int *iw = 0;
  const casadi_real* arg[12] = {0};
  casadi_real* res[1] = {0};
  if (argc>12) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"ceq1_v_func\" failed. Too many input arguments (%d, max 12)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"ceq1_v_func\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+547);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+2, casadi_s1, w+547);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+42, casadi_s2, w+547);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+222, casadi_s3, w+547);
  if (--argc>=0) arg[4] = casadi_from_mex(argv[4], w+223, casadi_s3, w+547);
  if (--argc>=0) arg[5] = casadi_from_mex(argv[5], w+224, casadi_s3, w+547);
  if (--argc>=0) arg[6] = casadi_from_mex(argv[6], w+225, casadi_s3, w+547);
  if (--argc>=0) arg[7] = casadi_from_mex(argv[7], w+226, casadi_s3, w+547);
  if (--argc>=0) arg[8] = casadi_from_mex(argv[8], w+227, casadi_s3, w+547);
  if (--argc>=0) arg[9] = casadi_from_mex(argv[9], w+228, casadi_s3, w+547);
  if (--argc>=0) arg[10] = casadi_from_mex(argv[10], w+229, casadi_s4, w+547);
  if (--argc>=0) arg[11] = casadi_from_mex(argv[11], w+289, casadi_s5, w+547);
  --resc;
  res[0] = w+309;
  i = ceq1_v_func(arg, res, iw, w+547, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"ceq1_v_func\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s6, res[0]);
}
#endif

casadi_int main_ceq1_v_func(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[621];
  const casadi_real* arg[12];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+2;
  arg[2] = w+42;
  arg[3] = w+222;
  arg[4] = w+223;
  arg[5] = w+224;
  arg[6] = w+225;
  arg[7] = w+226;
  arg[8] = w+227;
  arg[9] = w+228;
  arg[10] = w+229;
  arg[11] = w+289;
  res[0] = w+309;
  a = w;
  for (j=0; j<309; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = ceq1_v_func(arg, res, iw, w+547, 0);
  if (flag) return flag;
  r = w+309;
  for (j=0; j<238; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[12];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_ceq1_v_func(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "ceq1_v_func")==0) {
    mex_ceq1_v_func(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'ceq1_v_func'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "ceq1_v_func")==0) {
    return main_ceq1_v_func(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'ceq1_v_func'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
